services:
  docs:
    image: personal_website_local_docs
    container_name: personal_website_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./personal_website:/app/personal_website:z
    ports:
      - '9000:9000'
    command: /start-docs
