volumes:
  personal_website_local_postgres_data: {}
  personal_website_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: personal_website_local_django
    container_name: personal_website_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8001:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: personal_website_production_postgres
    container_name: personal_website_local_postgres
    volumes:
      - personal_website_local_postgres_data:/var/lib/postgresql/data
      - personal_website_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
